studies/views.py
import base64 as b64
import json
from urllib.parse import urlparse
from os.path import basename
import os

from flask import Blueprint, request, render_template, url_for, redirect, flash

from flask_login import current_user

#Import for jeh -> phase
from studies.forms import CreatePhases, TypeCreate, ProspectChoice, CreateStudy, CreateProspect, CreateContact, LabelsForm
import models as mo

#pylint: disable=too-many-statements
#pylint: disable=too-many-locals

from models.contact import Contact
from models.company import Company

studies_bp = Blueprint('studies_bp', __name__, template_folder='templates')

@studies_bp.before_request
def restrict_bp_to_admins():
    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))
    return None

#Study dashboard
#Tabs
@studies_bp.route('/dashboard', methods=['GET', 'POST'])
@studies_bp.route('/dashboard/<tab>', methods=['GET', 'POST'])
def dashboard(tab='all'):
    list_category = []
    for i in mo.labels.Labels.objects :
        if i.category not in list_category :
            list_category.append(i.category)

    if tab == 'all' :
        title = "Toutes les études"

    elif tab == 'progressing':
        title = "En cours"

    elif tab == 'finished':
        title = "Terminees"

    elif tab == 'failed':
        title = "Avortees"

    return render_template('dashboard.html',
            study=mo.study.Study.objects,
            labels=mo.labels.Labels.objects,
            list_category=list_category,
            title=title,
            tab=tab )

#Context function
@studies_bp.context_processor
def utility_processor():
    def get_info(id_study):
        total_price = 0
        tot_jeh = 0
        total_length = 0
        if id_study == '':
            return "Id non valide"

        sty = mo.study.Study.get(id_study)

        for i in sty.list_phases:
            total_price += i.price_jeh * i.nb_jeh
            tot_jeh += i.nb_jeh
            total_length += i.lenght_week

        return {"price":total_price,
                "tot_jeh": tot_jeh,
                "tot_weeks": total_length}

    def check_number_phase(list_phases):
        error = False
        list_number = []
        for i in list_phases:
            list_number.append(i.phase_number)

        num = 1
        while num < len(list_phases)+1 :
            if num not in list_number:
                error = True
            num +=1
        return error

    return dict(get_info=get_info, check_number_phase = check_number_phase)

@studies_bp.route('/create-study', methods=['GET', 'POST'])
def create_study():
    # We declare all forms we describe in the forms.py
    formLabel = LabelsForm(request.form)
    formCreateStudy = CreateStudy(request.form)
    formSubmit = TypeCreate(request.form)


    #Edit prospect
    list_prospect = Contact.get_all()
    formProspectChoice = ProspectChoice(request.form, obj=list_prospect)
    formProspectChoice.prospect_choice.choices = [(g.id, g.get_name()) for g in list_prospect]


    if request.method == 'POST':
        if request.form['btn'] == 'Valider' and formSubmit.structure_save.data == 'Non':
            # If the prospect doesn't exist, we create it
            return redirect(url_for(".create_prospect"))

        if request.form['btn'] ==  'Enregistrer':
            etu = mo.study.Study(
                number = 12, #change needed
                name = formCreateStudy.study_name.data,
                id_hubspot = formProspectChoice.prospect_choice.data,
                id_follower_quality = formCreateStudy.follower_quality.data,
                id_follower_study = formCreateStudy.follower_study.data,
                description = formCreateStudy.description.data,
                application_fees = 100,
                state = "Début",
                list_labels = [formLabel.year.data, formLabel.sector.data, formLabel.prospection.data] )
            etu.save()

            return redirect(url_for("index"))

    # If the prospect already exist, we have to choose it
    return render_template('createStudy.html',
    formCreateStudy=formCreateStudy,
    formLabel=formLabel,
    formSubmit=formSubmit,
    formProspectChoice=formProspectChoice )

@studies_bp.route('/create-prospect', methods=['GET', 'POST'])
def create_prospect():
    formCreateProspect = CreateProspect(request.form)
    formCreateContact = CreateContact(request.form)

    if request.method == 'POST':
        if request.form['btn'] ==  'Enregistrer':
            cont = mo.contacts.Contacts(
                first_name = formCreateContact.first_name.data,
                last_name = formCreateContact.name.data,
                job = formCreateContact.position.data,
                email = formCreateContact.email.data,
                phone = formCreateContact.phone.data )

            org = mo.organization.Organization(
                name = formCreateProspect.structure_name.data,
                adress = formCreateProspect.adresse.data,
                city = formCreateProspect.city.data,
                postal_code = formCreateProspect.postal_code.data,
                list_labels = [formCreateProspect.sector.data],
                list_contacts=[cont])
            org.save()

            return redirect(url_for(".create_study"))

    return render_template('createProspect.html',
    formCreateProspect=formCreateProspect,
    formCreateContact=formCreateContact )

#Study - Phases
@studies_bp.route('/<num_study>/phases', methods=['GET', 'POST'])
def phases(num_study=None):
    study = mo.study.Study.objects(number=num_study).first()

    #Form to create new phases
    form_create_phase = CreatePhases()

    #Sort phases by phase_number attribute
    study.list_phases.sort( key = lambda x : x.phase_number)

    #Initiate forms to edit phases
    list_form = []
    for i in study.list_phases :
        form = CreatePhases()
        list_form.append(form)


    #Forms to edit phases
    if request.method == 'GET':
        for j in range(len(study.list_phases)) :
            i = study.list_phases[j]
            form = list_form[j]

            form.name.data = i.name
            form.description.data = i.description
            form.lenght_week.data = i.lenght_week
            form.nb_jeh.data = i.nb_jeh
            form.price_jeh.data = i.price_jeh
            form.phase_number.data = i.phase_number
            form.control_point.data = i.control_point
            form.bill.data = i.bill



    if request.method == 'POST':

        #Request to create a phase
        if request.form['btn'] ==  'Enregistrer':
            if form_create_phase.validate_on_submit():
                phs = mo.phases.Phases(
                    name = form_create_phase.name.data,
                    description = form_create_phase.description.data,
                    lenght_week = form_create_phase.lenght_week.data,
                    nb_jeh = form_create_phase.nb_jeh.data,
                    price_jeh = form_create_phase.price_jeh.data,
                    phase_number = form_create_phase.phase_number.data,
                    control_point = form_create_phase.control_point.data,
                    bill = form_create_phase.bill.data,
                    ).save()
                #add link to mission
                study.list_phases.append(phs.id)
                study.save()

                flash("Phase created !")
            else:
                flash("Impossible to create phase, wrong data")

            return redirect(url_for('studies_bp.phases', num_study = study.number))

        #Request to delete a phase
        if request.form['btn'] ==  'Supprimer':
            id_delete = request.form['hidden']
            phs_del = mo.phases.Phases.get(id_delete)
            study.list_phases.remove(phs_del)
            study.save()
            phs_del.delete()

            return redirect(url_for('studies_bp.phases', num_study = study.number))

        #Request to edit a phase
        if request.form['btn'] ==  'Modifier':
            id_edit = request.form['hidden2']
            phs_edit = mo.phases.Phases.get(id_edit)
            form = list_form[int(request.form['hidden3'])]

            if form.validate_on_submit():
                phs_edit.name = form.name.data
                phs_edit.description = form.description.data
                phs_edit.lenght_week = form.lenght_week.data
                phs_edit.nb_jeh = form.nb_jeh.data
                phs_edit.price_jeh = form.price_jeh.data
                phs_edit.phase_number = form.phase_number.data
                phs_edit.control_point = form.control_point.data
                phs_edit.bill = form.bill.data

                phs_edit.save()
                flash("Phase edited !")

            else:
                flash("Impossible to edit phase, wrong data")

            return redirect(url_for('studies_bp.phases', num_study = study.number))

        #Request to add a JEH Maker link
        if request.form['btn'] ==  'Ajouter JEH':
            link = request.form['link-jeh']
            study.link_jeh = link
            study.save()

            #JSON from JEh
            obj = jeh_link_to_json(link)
            list_phase_json = obj['phases']

            #Drop current phase
            for phase in study.list_phases :
                phase.delete()

            study.list_phases = []

            #Create new phases
            for i in list_phase_json :
                phs = mo.phases.Phases(
                    phase_number = i["id"],
                    name = i["title"],
                    nb_jeh = i["nbJeh"],
                    price_jeh = i["jeh"],
                    lenght_week = 1
                ).save()

                study.list_phases.append(phs)
                study.save()

            return redirect(url_for('studies_bp.phases', num_study = study.number))


    return render_template('phases.html', study = study,
                        form_create_phase = form_create_phase,

templates/common/footer.html
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>IdéSYS - ERP : "Tous droits réservés"</span>
          </div>
        </div>
      </footer>

templates/common/header.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
   </button>
 <!-- 
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form> -->

    <ul class="navbar-nav ml-auto">
<!-- 
      <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-search fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
          <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
    
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i> 
          <span class="badge badge-danger badge-counter">3+</span>
        </a>

        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">
            Alerts Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-primary">
                <i class="fas fa-file-alt text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 12, 2019</div>
              <span class="font-weight-bold">A new monthly report is ready to download!</span>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-success">
                <i class="fas fa-donate text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 7, 2019</div>
              $290.29 has been deposited into your account!
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-warning">
                <i class="fas fa-exclamation-triangle text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 2, 2019</div>
              Spending Alert: We've noticed unusually high spending for your account.
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
        </div>
      </li>

      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
         
          <span class="badge badge-danger badge-counter">7</span>
        </a>
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">
            Message Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
              <div class="status-indicator bg-success"></div>
            </div>
            <div class="font-weight-bold">
              <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
              <div class="small text-gray-500">Emily Fowler · 58m</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
              <div class="status-indicator"></div>
            </div>
            <div>
              <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
              <div class="small text-gray-500">Jae Chun · 1d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
              <div class="status-indicator bg-warning"></div>
            </div>
            <div>
              <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
              <div class="small text-gray-500">Morgan Alvarez · 2d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
              <div class="status-indicator bg-success"></div>
            </div>
            <div>
              <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
              <div class="small text-gray-500">Chicken the Dog · 2w</div>
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
        </div>
      </li>

      <div class="topbar-divider d-none d-sm-block"></div> -->

      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{current_user.name}}</span>
          <img alt="Google profile pic" class="img-profile rounded-circle" src="{{current_user.profile_pic}}">
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{{ url_for('auth_bp.user')}}">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profil
          </a>
          <!-- 
          <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
          </a>
          <div class="dropdown-divider"></div> -->
          <a class="dropdown-item" href="{{ url_for('auth_bp.logout') }}">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Déconnexion
          </a>
        </div>
      </li>

    </ul>

  </nav>

templates/common/sidebar.html
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon">
          <img src="{{url_for('static',filename='img/logoblanc.png')}}" height="45">
        </div>
        <div class="sidebar-brand-text mx-3">IdéSYS ERP</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- A FAIRE -->
      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Nav Item - Gestion asso -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-address-book"></i>
          <span>Gestion associative</span></a>
      </li>

      <!-- A FAIRE -->
      <!-- Nav Item - Suivi d'étude dropdown -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-cog"></i>
          <span>Suivi d'étude</span></a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner animated--grow-in rounded">
            <a class="collapse-item" href="{{ url_for('studies_bp.dashboard', tab='all') }}"">Voir les études</a>
            <a class="collapse-item" href="{{ url_for('studies_bp.create_study') }}">Créer une étude</a>
            <a class="collapse-item" href="/">Chiffre d'affaire</a>
          </div>
        </div>
      </li>


      <!-- A FAIRE -->
      <!-- Nav Item - Prospection -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-comments"></i>
          <span>Prospection</span></a>
      </li>

      <!-- A FAIRE -->
      <!-- Nav Item - Pilotage -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Pilotage de la J.E.</span></a>
      </li>

      <!-- A FAIRE -->
      <!-- Nav Item - Config -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Configuration</span></a>
      </li>

      <!-- A FAIRE -->
      <!-- Nav Item - Admin -->
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-folder-open "></i>
          <span>Administration</span></a>
      </li>

      <!-- Bouton pour faire apparaitre -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->